### ISSUE TITLE
Add ~medals~ trophies to activity records, in slack messages

### ISSUE THREAD

**Issue by caarmen** [caarmen/slack-health-bot#58]
~When an activity is posted to slack, include one of the following icons, if applicable, next to the different attributes of the activity:~
* ~🥇 If this attribute has the best value for this user and activity type~
* ~🥈 If this attribute has the second best value for this user and activity type~
* ~🥉 If this attribute has the third best value for this user and activity type~

~Include the icon on the following attributes for fitbit activities:~
* ~calories (highest)~
* ~total_minutes (highest)~
* ~fat_burn_minutes (highest)~
* ~cardio_minutes (highest)~
* ~peak_minutes (highest)~

When an activity is posted to slack, include an optional text and trophy icon 🏆 next to the following attributes:
* calories
* total_minutes
* fat_burn_minutes
* cardio_minutes
* peak_minutes

The optional text to include for each item is:
* "New all-time record! 🏆", if this is the best value ever recorded for this user and activity type
* "New record (last `X` days)! 🏆", if this is the best value recorded over the last `X` days for this user and activity type 

`X` is to be configured in the `.env.template` variable `FITBIT_ACTIVITY_RECORD_HISTORY_DAYS` with a default value of `180`.

**Comment by BoD** [comment]
For the 2nd one, text should be "New record (last x days)!"

**Comment by caarmen** [comment]
Available in release v1.5.0:
* https://github.com/caarmen/slack-health-bot/releases/tag/v1.5.0
